{ config, lib, ... }:

{
  # NVIDIA Container Toolkit (CDI)
  #
  # Docker 25+ exposes GPUs through the Container Device Interface: a container
  # asks for one with `devices: ["nvidia.com/gpu=all"]`, and the daemon reads
  # the device nodes and driver libraries from the CDI spec generated here.
  # Enabling this also sets `features.cdi` in the daemon config. The legacy
  # `virtualisation.docker.enableNvidia` runtime wrapper is not used: both
  # Docker 29.8.1 and the pinned nvidia-container-toolkit are CDI based, and
  # without the spec generated by this module dockerd rejects the device
  # request and llama.cpp starts without CUDA.
  hardware.nvidia-container-toolkit.enable = true;

  # Docker data root on /home
  #
  # / has 19 GB free; the CUDA llama.cpp image plus its layers and the model
  # cache do not fit there. /home has 136 GB. Nothing else writes to
  # /var/lib/docker any more once this is set, so the old images there stay
  # behind and have to be pulled again into the new root.
  virtualisation.docker.daemon.settings."data-root" = "/home/docker";

  # /home is a separate filesystem, and dockerd happily creates its data root
  # before that mount exists, which would put a second, empty root on the root
  # filesystem and fill / again. RequiresMountsFor adds the Requires/After pair
  # for home.mount to docker.service.
  systemd.services.docker.unitConfig.RequiresMountsFor = "/home/docker";

  # Declare the data root so it exists with root-only permissions on every
  # boot, instead of relying on dockerd to create it at whatever moment it
  # starts.
  systemd.tmpfiles.rules = [ "d /home/docker 0700 root root -" ];

  # Tailnet exposure
  #
  # `tailscale serve` proxies the loopback-only port onto the tailnet, so the
  # container never has to bind a Tailscale address. Binding one made the whole
  # container fail to start whenever that address was not assigned yet, which
  # also took the loopback binding down and broke the local agent. The proxy is
  # lazy: with the container stopped the tailnet gets a gateway error and the
  # exposure itself stays up.
  systemd.services.tailscale-serve-llama = {
    description = "Expose the local llama.cpp server to the tailnet";
    # Applied only after tailscaled is up. `tailscale serve` with the same
    # arguments is idempotent, so re-running it on every boot is safe.
    requires = [ "tailscaled.service" ];
    after = [ "tailscaled.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${lib.getExe config.services.tailscale.package} serve --bg --tcp=21434 tcp://127.0.0.1:21434";
    };
  };

  # Inbound TCP on tailscale0 is dropped by nixos-fw, so the port the serve
  # forward listens on, 21434 (the tailnet side of the forward above), is
  # allowed on that interface. `tailscale serve` normally handles peer
  # connections in-process before the kernel sees them, so this mainly covers
  # a kernel-delivered connection; either way it opens nothing the serve
  # config does not already expose. Scoped to the one port on purpose:
  # trusting tailscale0 would also open ssh and every other host listener to
  # the whole tailnet.
  networking.firewall.interfaces.tailscale0.allowedTCPPorts = [ 21434 ];
}
