# The Construct: AMD Ryzen 5600 + NVIDIA RTX 3060 Ti
{ config, pkgs, ... }:

{
  imports = [
    ../hardware/theConstruct.nix
    ../hardware/theConstruct-gen.nix  # Generated by nixos-generate-config
    ../configuration.nix
  ];

  networking.hostName = "theConstruct";

  programs.steam = {
    enable = true;
    gamescope.enable = true;
    remotePlay.openFirewall = true;
    dedicatedServer.openFirewall = true;
  };
}
